services:
  - type: web
    name: pot-ticketing-api
    runtime: docker
    region: frankfurt
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
